In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('Fake.csv')

In [3]:
df.head()

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   

                date  
0  December 31, 2017  
1  December 31, 2017  
2  December 30, 2017  
3  December 29, 2017  
4  December 25, 2017

In [4]:
df['subject'].unique()

array(['News', 'politics', 'Government News', 'left-news', 'US_News',
       'Middle-east'], dtype=object)

In [5]:
df=df.drop('date',axis=1)

In [6]:
df.head()

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   

                                                text subject  
0  Donald Trump just couldn t wish all Americans ...    News  
1  House Intelligence Committee Chairman Devin Nu...    News  
2  On Friday, it was revealed that former Milwauk...    News  
3  On Christmas day, Donald Trump announced that ...    News  
4  Pope Francis used his annual Christmas Day mes...    News

In [7]:
df.shape

(23481, 3)

In [8]:
df.isnull().sum()

title      0
text       0
subject    0
dtype: int64

In [9]:
df.duplicated().sum()

4

In [10]:
df.drop_duplicates(inplace=True)

In [11]:
df.head()

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   

                                                text subject  
0  Donald Trump just couldn t wish all Americans ...    News  
1  House Intelligence Committee Chairman Devin Nu...    News  
2  On Friday, it was revealed that former Milwauk...    News  
3  On Christmas day, Donald Trump announced that ...    News  
4  Pope Francis used his annual Christmas Day mes...    News

In [12]:
## divide the independent and dependent fetures
x=df.drop('subject',axis=1)

In [13]:
y=df['subject']

In [14]:
x.head()

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   

                                                text  
0  Donald Trump just couldn t wish all Americans ...  
1  House Intelligence Committee Chairman Devin Nu...  
2  On Friday, it was revealed that former Milwauk...  
3  On Christmas day, Donald Trump announced that ...  
4  Pope Francis used his annual Christmas Day mes...

In [15]:
y

0               News
1               News
2               News
3               News
4               News
            ...     
23476    Middle-east
23477    Middle-east
23478    Middle-east
23479    Middle-east
23480    Middle-east
Name: subject, Length: 23477, dtype: object

In [16]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
y=encoder.fit_transform(y)

In [19]:
y

array([2, 2, 2, ..., 1, 1, 1])

In [20]:
x.shape

(23477, 2)

In [21]:
y.shape

(23477,)

In [22]:
import tensorflow as tf
print(tf.__version__)

2.13.0


In [24]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Dense,LSTM
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot

In [25]:
## vocabulary size
voc_size=5000

 ### one hot representation

In [27]:
messages=x.copy()

In [28]:
messages['title'][1]

' Drunk Bragging Trump Staffer Started Russian Collusion Investigation'

In [29]:
messages

title  \
0       Donald Trump Sends Out Embarrassing New Year’...   
1       Drunk Bragging Trump Staffer Started Russian ...   
2       Sheriff David Clarke Becomes An Internet Joke...   
3       Trump Is So Obsessed He Even Has Obama’s Name...   
4       Pope Francis Just Called Out Donald Trump Dur...   
...                                                  ...   
23476  McPain: John McCain Furious That Iran Treated ...   
23477  JUSTICE? Yahoo Settles E-mail Privacy Class-ac...   
23478  Sunnistan: US and Allied ‘Safe Zone’ Plan to T...   
23479  How to Blow $700 Million: Al Jazeera America F...   
23480  10 U.S. Navy Sailors Held by Iranian Military ...   

                                                    text  
0      Donald Trump just couldn t wish all Americans ...  
1      House Intelligence Committee Chairman Devin Nu...  
2      On Friday, it was revealed that former Milwauk...  
3      On Christmas day, Donald Trump announced that ...  
4      Pope Francis used his annual Christmas Day mes...  
...                                                  ...  
23476  21st Century Wire says As 21WIRE reported earl...  
23477  21st Century Wire says It s a familiar theme. ...  
23478  Patrick Henningsen  21st Century WireRemember ...  
23479  21st Century Wire says Al Jazeera America will...  
23480  21st Century Wire says As 21WIRE predicted in ...  

[23477 rows x 2 columns]

In [31]:
import nltk
import re
from nltk.corpus import stopwords

In [33]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [37]:
messages.reset_index(inplace=True)

In [38]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer ##stemming purpose
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [39]:
corpus

['donald trump send embarrass new year eve messag disturb',
 'drunk brag trump staffer start russian collus investig',
 'sheriff david clark becom internet joke threaten poke peopl eye',
 'trump obsess even obama name code websit imag',
 'pope franci call donald trump christma speech',
 'racist alabama cop brutal black boy handcuff graphic imag',
 'fresh golf cours trump lash fbi deputi director jame comey',
 'trump said insan racist stuff insid oval offic wit back',
 'former cia director slam trump un bulli openli suggest act like dictat tweet',
 'watch brand new pro trump ad featur much kiss make sick',
 'papa john founder retir figur racism bad busi',
 'watch paul ryan told us care struggl famili live blue state',
 'bad news trump mitch mcconnel say repeal obamacar',
 'watch lindsey graham trash media portray trump kooki forget word',
 'heiress disney empir know gop scam us shred tax bill',
 'tone deaf trump congrat rep scalis lose weight almost die',
 'internet brutal mock disney n

In [40]:
corpus[1]

'drunk brag trump staffer start russian collus investig'

In [41]:
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr

[[3456, 740, 2595, 3357, 2891, 3834, 261, 1383, 3957],
 [648, 950, 740, 264, 541, 2564, 510, 4447],
 [923, 2600, 4131, 644, 4494, 4424, 4563, 109, 4899, 3966],
 [740, 2045, 1221, 418, 3606, 4371, 4102, 3297],
 [448, 4186, 4423, 3456, 740, 974, 2884],
 [3853, 3100, 3845, 844, 2296, 29, 2184, 3659, 3297],
 [2063, 76, 664, 740, 4183, 3701, 236, 453, 102, 4018],
 [740, 66, 2214, 3853, 2081, 1458, 2935, 2243, 4700, 157],
 [4735, 3330, 453, 665, 740, 552, 1045, 3170, 4948, 4617, 1763, 874, 328],
 [3501, 4635, 2891, 4651, 740, 4688, 1170, 3077, 469, 715, 1078],
 [394, 2619, 2286, 3450, 1591, 1529, 1731, 4759],
 [3501, 4134, 3081, 3453, 2786, 239, 1329, 219, 2631, 1981, 2722],
 [1731, 3380, 740, 711, 441, 3288, 1671, 4899],
 [3501, 4777, 49, 2440, 4902, 3958, 740, 1188, 1019, 3119],
 [4202, 3976, 1477, 3968, 1484, 1524, 2786, 175, 3337, 230],
 [1286, 4425, 740, 4314, 3548, 3049, 4743, 4579, 673, 1996],
 [4494, 844, 2749, 3976, 2891, 740, 4998, 723, 3781],
 [2357, 2750, 1216, 4606, 3456, 740, 9

In [42]:
corpus[2]

'sheriff david clark becom internet joke threaten poke peopl eye'

In [43]:
onehot_repr[2]

[923, 2600, 4131, 644, 4494, 4424, 4563, 109, 4899, 3966]

 Embedding Representation

In [44]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[3456  740 2595 ...    0    0    0]
 [ 648  950  740 ...    0    0    0]
 [ 923 2600 4131 ...    0    0    0]
 ...
 [2761 2786  840 ...    0    0    0]
 [ 167 1122 4951 ...    0    0    0]
 [2665 3223  573 ...    0    0    0]]


In [45]:
embedded_docs[2]

array([ 923, 2600, 4131,  644, 4494, 4424, 4563,  109, 4899, 3966,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0], dtype=int32)

In [89]:
### create a model
embedding_vector_features=40 ##features representation
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(6,activation='softmax'))
model.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_8 (Embedding)     (None, 20, 40)            200000    
                                                                 
 lstm_8 (LSTM)               (None, 100)               56400     
                                                                 
 dense_6 (Dense)             (None, 6)                 606       
                                                                 
Total params: 257006 (1003.93 KB)
Trainable params: 257006 (1003.93 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [90]:
len(embedded_docs),y.shape

(23477, (23477,))

In [91]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [92]:
X_final.shape,y_final.shape

((23477, 20), (23477,))

In [93]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [94]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
246/246 [==============================] - 17s 58ms/step - loss: 1.2263 - accuracy: 0.5045 - val_loss: 1.0379 - val_accuracy: 0.5740
Epoch 2/10
246/246 [==============================] - 3s 12ms/step - loss: 0.9309 - accuracy: 0.6063 - val_loss: 0.9966 - val_accuracy: 0.5845
Epoch 3/10
246/246 [==============================] - 2s 8ms/step - loss: 0.8563 - accuracy: 0.6247 - val_loss: 0.9818 - val_accuracy: 0.5865
Epoch 4/10
246/246 [==============================] - 3s 12ms/step - loss: 0.8024 - accuracy: 0.6396 - val_loss: 0.9933 - val_accuracy: 0.5943
Epoch 5/10
246/246 [==============================] - 3s 13ms/step - loss: 0.7651 - accuracy: 0.6496 - val_loss: 1.0065 - val_accuracy: 0.5929
Epoch 6/10
246/246 [==============================] - 3s 13ms/step - loss: 0.7296 - accuracy: 0.6576 - val_loss: 1.0282 - val_accuracy: 0.5951
Epoch 7/10
246/246 [==============================] - 2s 8ms/step - loss: 0.6979 - accuracy: 0.6695 - val_loss: 1.0618 - val_accuracy: 0.5871


In [95]:
y_pred=model.predict(X_test)

243/243 [==============================] - 1s 3ms/step


In [96]:
y_pred=np.where(y_pred > 0.6, 1,0) ##AUC ROC Curve

In [100]:
## using machine learning
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()


In [102]:
classifier.fit(X_train,y_train)

RandomForestClassifier()

In [104]:
y_pred=classifier.predict(X_test)

In [105]:
y_pred

array([4, 5, 4, ..., 2, 2, 2])

In [106]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       520
           1       0.01      0.01      0.01       258
           2       0.68      0.90      0.78      2996
           3       0.03      0.03      0.03       235
           4       0.07      0.05      0.06      1492
           5       0.22      0.20      0.21      2247

    accuracy                           0.42      7748
   macro avg       0.17      0.20      0.18      7748
weighted avg       0.34      0.42      0.37      7748



In [107]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.4183014971605576

In [ ]:
## accuracy is not good but main motive how to model create and run.using hyperparameter accuracy will be a high...